spring.application.name=libraryJet
#Postgresql configuration
spring.datasource.url=jdbc:postgresql://localhost:5460/postgres
spring.datasource.username=myuser
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
server.port=8040